### PR TITLE
Typo fix in README

### PR DESCRIPTION
**Pull request by blegat**

### CODE REVIEW

**Comment by saschatimme** [comment]
That's a service!

**Comment by saschatimme** [comment]
Is the new API understandable in your opinion? @blegat

**Comment by blegat** [comment]
Yes, it is a lot clearer ! Although I am wondering: Why are they named `Config` ?

**Comment by saschatimme** [comment]
I took the name from `ForwardDiff.jl`, but now I start to doubt the naming. Maybe `Cache` instead?

**Comment by blegat** [comment]
Yes, `Cache` would also be what I would have picked. Consistency with ForwardDiff is also a good idea though.

**Comment by saschatimme** [comment]
I think I will go with `Config` since the endgame would be to just use AD if works out performance wise and supports complex arguments.

**Pull request merged**
